### ISSUE TITLE
feat(bug): Locale Select Menu (Not Active)

### ISSUE THREAD

**Issue by Littie6amer** [MetroReviews/Website#14]
**Describe the bug**
When I go to switch languages, it still says English is selected even when the site isn't actually in English.

**To Reproduce**
1. Go to the language selector
2. Click on a language that isn't English

**Expected behavior**
The language selector says that the language is selected and not English 

**Smartphone (please complete the following information):**
 - Device: Google Pixel 4xl
 - OS: Android 12
 - Browser: Chrome
 - Version: 103.0

**Comment by TheRealToxicDev** [comment]
Will look into a fix for this.

**Comment by TheRealToxicDev** [comment]
> **Describe the bug** When I go to switch languages, it still says English is selected even when the site isn't actually in English.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Go to the language selector
> 2. Click on a language that isn't English
> 
> **Expected behavior** The language selector says that the language is selected and not English
> 
> **Smartphone (please complete the following information):**
> 
> * Device: Google Pixel 4xl
> * OS: Android 12
> * Browser: Chrome
> * Version: 103.0

Issue fixed in commit: c33488d91a6ded67e8373eb28573d655edd08701

**Comment by TheRealToxicDev** [comment]
Reference if needed!~

**Comment by TheRealToxicDev** [comment]
Hmmm
