### ISSUE TITLE
Top left picture won't render..

### ISSUE THREAD

**Issue by Miya25** [MetroReviews/Website#3]
![image](https://user-images.githubusercontent.com/87431619/168063778-7cb31d19-26c0-4e16-9ecc-4c0743bbb14d.png)

**Comment by TheRealToxicDev** [comment]
> ![image](https://user-images.githubusercontent.com/87431619/168063778-7cb31d19-26c0-4e16-9ecc-4c0743bbb14d.png)

Cause it doesn’t exist yet 🤷

**Comment by TheRealToxicDev** [comment]
> ![image](https://user-images.githubusercontent.com/87431619/168063778-7cb31d19-26c0-4e16-9ecc-4c0743bbb14d.png)

Cause it doesn’t exist yet 🤷

**Comment by Miya25** [comment]
ohhh oki
